<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="g_vector_float">
        <xs:list itemType="xs:float"/>
    </xs:simpleType>

    <xs:simpleType name="g_string">
        <xs:annotation><xs:appinfo><typeStr>String</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="g_string_list">
        <xs:annotation><xs:appinfo><typeStr>One or more strings separated by a single whitespace</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="\S+( \S+)*"/>
            <xs:whiteSpace value="preserve"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="g_l10n_string">
        <xs:annotation><xs:appinfo><typeStr>String or l10n key</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="g_filename">
        <xs:annotation><xs:appinfo><typeStr>Path to a certain file</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="g_float">
        <xs:annotation><xs:appinfo><typeStr>Float</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:float"/>
    </xs:simpleType>

    <xs:simpleType name="g_angle">
        <xs:annotation><xs:appinfo><typeStr>Angle</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:float"/>
    </xs:simpleType>

    <xs:simpleType name="g_time">
        <xs:annotation><xs:appinfo><typeStr>Time in seconds</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:float"/>
    </xs:simpleType>

    <xs:simpleType name="g_day_time">
        <xs:annotation><xs:appinfo><typeStr>Time hh:mm:ss.sss format</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:time"/>
    </xs:simpleType>

    <xs:simpleType name="g_int">
        <xs:annotation><xs:appinfo><typeStr>Integer</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:integer"/>
    </xs:simpleType>

    <xs:simpleType name="g_uint">
        <xs:annotation><xs:appinfo><typeStr>Integer (unsigned)</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:integer"/>
    </xs:simpleType>

    <xs:simpleType name="g_bool">
        <xs:annotation><xs:appinfo><typeStr>Boolean</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="true|false"/>
            <xs:whiteSpace value="preserve"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="g_node_index">
        <xs:annotation><xs:appinfo><typeStr>Index to i3d node or i3d mapping identifier</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="g_node_indices">
        <xs:annotation><xs:appinfo><typeStr>List of indices to i3d nodes or i3d mapping identifiers</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="g_vector_2">
        <xs:annotation><xs:appinfo><typeStr>Multiple values (x, y)</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="g_vector_float">
            <xs:pattern value="\S+ \S+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="g_vector_3">
        <xs:annotation><xs:appinfo><typeStr>Multiple values (x, y, z)</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="g_vector_float">
            <xs:pattern value="\S+ \S+ \S+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="g_vector_4">
        <xs:annotation><xs:appinfo><typeStr>Multiple values (x, y, z, w)</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="g_vector_float">
            <xs:pattern value="\S+ \S+ \S+ \S+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="g_vector_n">
        <xs:annotation><xs:appinfo><typeStr>Multiple values</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="g_vector_float"/>
    </xs:simpleType>

    <xs:simpleType name="g_vector_trans">
        <xs:annotation><xs:appinfo><typeStr>Translation values (x, y, z)</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="g_vector_float">
            <xs:pattern value="\S+ \S+ \S+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="g_vector_rot">
        <xs:annotation><xs:appinfo><typeStr>Rotation values (x, y, z)</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="g_vector_float">
            <xs:pattern value="\S+ \S+ \S+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="g_vector_rot_2">
        <xs:annotation><xs:appinfo><typeStr>Rotation values (x, y)</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="g_vector_float">
            <xs:pattern value="\S+ \S+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="g_vector_scale">
        <xs:annotation><xs:appinfo><typeStr>Scale values (x, y, z)</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="g_vector_float">
            <xs:pattern value="\S+ \S+ \S+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="g_color">
        <xs:annotation><xs:appinfo><typeStr>Color values (r, g, b) or brand color id</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="g_vehicle_material">
        <xs:annotation><xs:appinfo><typeStr>Name of brand material template or color values (r,g,b)</typeStr></xs:appinfo></xs:annotation>
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:element name="beaconLight">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="device" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="brightnessScale" type="g_float">
                            <xs:annotation><xs:documentation xml:lang="en">Real beacon brightness factor (0-1)</xs:documentation></xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="mode" type="g_string">
                            <xs:annotation><xs:documentation xml:lang="en">Real beacon light mode</xs:documentation></xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="numLEDScale" type="g_float">
                            <xs:annotation><xs:documentation xml:lang="en">Real beacon num led factor (0-1)</xs:documentation></xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="rpm" type="g_float">
                            <xs:annotation><xs:documentation xml:lang="en">Real beacon rpm</xs:documentation></xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="filename" type="g_string" minOccurs="1">
                    <xs:annotation><xs:documentation xml:lang="en">Path to i3d file</xs:documentation></xs:annotation>
                </xs:element>
                <xs:element name="i3dMappings" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="i3dMapping" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" type="g_string">
                                        <xs:annotation><xs:documentation xml:lang="en">Identifier to be used in xml</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="node" type="g_string">
                                        <xs:annotation><xs:documentation xml:lang="en">Index path to node in i3d file</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="material" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="clearCoat" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="intensity" type="g_float">
                                        <xs:annotation><xs:documentation xml:lang="en">Intensity of clear coat</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="smoothness" type="g_float">
                                        <xs:annotation><xs:documentation xml:lang="en">Smoothness of clear coat</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="colorScale" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="value" type="g_string">
                                        <xs:annotation><xs:documentation xml:lang="en">Material color if it should not be used from configuration (can also be a different material template, from which then ONLY the color is taken)</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="detail" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="diffuse" type="g_filename">
                                        <xs:annotation><xs:documentation xml:lang="en">Path to detail diffuse texture</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="normal" type="g_filename">
                                        <xs:annotation><xs:documentation xml:lang="en">Path to detail normal texture</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="specular" type="g_filename">
                                        <xs:annotation><xs:documentation xml:lang="en">Path to detail specular texture</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="metalness" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="value" type="g_float">
                                        <xs:annotation><xs:documentation xml:lang="en">Metalness value</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="smoothness" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="value" type="g_float">
                                        <xs:annotation><xs:documentation xml:lang="en">Smoothness value</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="textures" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="diffuse" type="g_filename">
                                        <xs:annotation><xs:documentation xml:lang="en">Path to diffuse texture</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="normal" type="g_filename">
                                        <xs:annotation><xs:documentation xml:lang="en">Path to normal texture</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="specular" type="g_filename">
                                        <xs:annotation><xs:documentation xml:lang="en">Path to specular texture</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute name="materialSlotName" type="g_string">
                            <xs:annotation><xs:documentation xml:lang="en">Material slot name in the i3d file</xs:documentation></xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="materialTemplateName" type="g_string">
                            <xs:annotation>
                                <xs:documentation xml:lang="en">Name of template to apply (all attributes will be used from template)</xs:documentation>
                                <xs:appinfo>
                                    <typeStr>String</typeStr>
                                    <giantsAutoCompletion sourceFile="$data/shared/brandMaterialTemplates.xml" prefix="">
                                        <path>templates.template#name</path>
                                    </giantsAutoCompletion>
                                </xs:appinfo>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="materialTemplateUseColorOnly" type="g_bool" default="false">
                            <xs:annotation><xs:documentation xml:lang="en">If &apos;true&apos;, only the color is used from the material template. The rest from the i3d file.</xs:documentation></xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="mountTypes" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="mountType" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="name" type="g_string">
                                        <xs:annotation><xs:documentation xml:lang="en">Name of the mount type</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="node" type="g_node_index">
                                        <xs:annotation><xs:documentation xml:lang="en">Node to show while this mount type is used</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="yOffset" type="g_float" default="0">
                                        <xs:annotation><xs:documentation xml:lang="en">Y translation offset of the while beacon light while this mount type is used</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="parentFile" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="attributes" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:element name="clearList" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="keepIndex" type="g_int">
                                                    <xs:annotation><xs:documentation xml:lang="en">Index of list to keep</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="path" type="g_string">
                                                    <xs:annotation><xs:documentation xml:lang="en">List to clear but keep one item</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="remove" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="path" type="g_string">
                                                    <xs:annotation><xs:documentation xml:lang="en">Path to remove from parent xml</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="set" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="path" type="g_string">
                                                    <xs:annotation><xs:documentation xml:lang="en">Path change in parent xml</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="value" type="g_string">
                                                    <xs:annotation><xs:documentation xml:lang="en">Target value to set in parent file</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute name="xmlFilename" type="g_string">
                            <xs:annotation><xs:documentation xml:lang="en">Parent xml filepath used as basis</xs:documentation></xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="realLight" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="node" type="g_node_index">
                            <xs:annotation><xs:documentation xml:lang="en">Real light source node</xs:documentation></xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="useRealLight" type="g_bool" default="true">
                            <xs:annotation><xs:documentation xml:lang="en">Defines if the real light is used at all for this variation</xs:documentation></xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rootNode" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="node" type="g_node_index">
                            <xs:annotation><xs:documentation xml:lang="en">Root node</xs:documentation></xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rotator" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="node" type="g_node_index">
                            <xs:annotation><xs:documentation xml:lang="en">Node that is rotating</xs:documentation></xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="speed" type="g_float" default="0.015">
                            <xs:annotation><xs:documentation xml:lang="en">Rotating speed</xs:documentation></xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="staticLight" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="intensityScale" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="maxDistance" type="g_float">
                                        <xs:annotation><xs:documentation xml:lang="en">Reference distance for max intensity</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="maxIntensity" type="g_float">
                                        <xs:annotation><xs:documentation xml:lang="en">Intensity to be used at max. distance</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="minDistance" type="g_float">
                                        <xs:annotation><xs:documentation xml:lang="en">Reference distance for default intensity</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="minIntensity" type="g_float">
                                        <xs:annotation><xs:documentation xml:lang="en">Intensity to be used at min. distance</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute name="intensity" type="g_float" default="100">
                            <xs:annotation><xs:documentation xml:lang="en">Light intensity of shader node</xs:documentation></xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="minDistance" type="g_float" default="0">
                            <xs:annotation><xs:documentation xml:lang="en">Starting from this camera distance to static light is visible</xs:documentation></xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="multiBlink" type="g_bool" default="false">
                            <xs:annotation><xs:documentation xml:lang="en">Uses multiblink functionality</xs:documentation></xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="multiBlinkParameters" type="g_vector_4" default="2 5 50 0">
                            <xs:annotation><xs:documentation xml:lang="en">Parameters for multi blink function (blink ticks, pause ticks, frequency)</xs:documentation></xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="node" type="g_node_index">
                            <xs:annotation><xs:documentation xml:lang="en">Light control shader node</xs:documentation></xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="uvOffsetParameter" type="g_int" default="0">
                            <xs:annotation><xs:documentation xml:lang="en">Parameter for light UV offset bit mask</xs:documentation></xs:annotation>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="variations" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="variation" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:element name="device" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:attribute name="brightnessScale" type="g_float">
                                                    <xs:annotation><xs:documentation xml:lang="en">Real beacon brightness factor (0-1)</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="mode" type="g_string">
                                                    <xs:annotation><xs:documentation xml:lang="en">Real beacon light mode</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="numLEDScale" type="g_float">
                                                    <xs:annotation><xs:documentation xml:lang="en">Real beacon num led factor (0-1)</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="rpm" type="g_float">
                                                    <xs:annotation><xs:documentation xml:lang="en">Real beacon rpm</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="material" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="clearCoat" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:attribute name="intensity" type="g_float">
                                                                <xs:annotation><xs:documentation xml:lang="en">Intensity of clear coat</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                            <xs:attribute name="smoothness" type="g_float">
                                                                <xs:annotation><xs:documentation xml:lang="en">Smoothness of clear coat</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="colorScale" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:attribute name="value" type="g_string">
                                                                <xs:annotation><xs:documentation xml:lang="en">Material color if it should not be used from configuration (can also be a different material template, from which then ONLY the color is taken)</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="detail" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:attribute name="diffuse" type="g_filename">
                                                                <xs:annotation><xs:documentation xml:lang="en">Path to detail diffuse texture</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                            <xs:attribute name="normal" type="g_filename">
                                                                <xs:annotation><xs:documentation xml:lang="en">Path to detail normal texture</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                            <xs:attribute name="specular" type="g_filename">
                                                                <xs:annotation><xs:documentation xml:lang="en">Path to detail specular texture</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="metalness" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:attribute name="value" type="g_float">
                                                                <xs:annotation><xs:documentation xml:lang="en">Metalness value</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="smoothness" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:attribute name="value" type="g_float">
                                                                <xs:annotation><xs:documentation xml:lang="en">Smoothness value</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="textures" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:attribute name="diffuse" type="g_filename">
                                                                <xs:annotation><xs:documentation xml:lang="en">Path to diffuse texture</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                            <xs:attribute name="normal" type="g_filename">
                                                                <xs:annotation><xs:documentation xml:lang="en">Path to normal texture</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                            <xs:attribute name="specular" type="g_filename">
                                                                <xs:annotation><xs:documentation xml:lang="en">Path to specular texture</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:all>
                                                <xs:attribute name="materialSlotName" type="g_string">
                                                    <xs:annotation><xs:documentation xml:lang="en">Material slot name in the i3d file</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="materialTemplateName" type="g_string">
                                                    <xs:annotation>
                                                        <xs:documentation xml:lang="en">Name of template to apply (all attributes will be used from template)</xs:documentation>
                                                        <xs:appinfo>
                                                            <typeStr>String</typeStr>
                                                            <giantsAutoCompletion sourceFile="$data/shared/brandMaterialTemplates.xml" prefix="">
                                                                <path>templates.template#name</path>
                                                            </giantsAutoCompletion>
                                                        </xs:appinfo>
                                                    </xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="materialTemplateUseColorOnly" type="g_bool" default="false">
                                                    <xs:annotation><xs:documentation xml:lang="en">If &apos;true&apos;, only the color is used from the material template. The rest from the i3d file.</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="realLight" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:attribute name="node" type="g_node_index">
                                                    <xs:annotation><xs:documentation xml:lang="en">Real light source node</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="useRealLight" type="g_bool" default="true">
                                                    <xs:annotation><xs:documentation xml:lang="en">Defines if the real light is used at all for this variation</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="rotator" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:attribute name="node" type="g_node_index">
                                                    <xs:annotation><xs:documentation xml:lang="en">Node that is rotating</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="speed" type="g_float" default="0.015">
                                                    <xs:annotation><xs:documentation xml:lang="en">Rotating speed</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="staticLight" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="intensityScale" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:attribute name="maxDistance" type="g_float">
                                                                <xs:annotation><xs:documentation xml:lang="en">Reference distance for max intensity</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                            <xs:attribute name="maxIntensity" type="g_float">
                                                                <xs:annotation><xs:documentation xml:lang="en">Intensity to be used at max. distance</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                            <xs:attribute name="minDistance" type="g_float">
                                                                <xs:annotation><xs:documentation xml:lang="en">Reference distance for default intensity</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                            <xs:attribute name="minIntensity" type="g_float">
                                                                <xs:annotation><xs:documentation xml:lang="en">Intensity to be used at min. distance</xs:documentation></xs:annotation>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:all>
                                                <xs:attribute name="intensity" type="g_float" default="100">
                                                    <xs:annotation><xs:documentation xml:lang="en">Light intensity of shader node</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="minDistance" type="g_float" default="0">
                                                    <xs:annotation><xs:documentation xml:lang="en">Starting from this camera distance to static light is visible</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="multiBlink" type="g_bool" default="false">
                                                    <xs:annotation><xs:documentation xml:lang="en">Uses multiblink functionality</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="multiBlinkParameters" type="g_vector_4" default="2 5 50 0">
                                                    <xs:annotation><xs:documentation xml:lang="en">Parameters for multi blink function (blink ticks, pause ticks, frequency)</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="node" type="g_node_index">
                                                    <xs:annotation><xs:documentation xml:lang="en">Light control shader node</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                                <xs:attribute name="uvOffsetParameter" type="g_int" default="0">
                                                    <xs:annotation><xs:documentation xml:lang="en">Parameter for light UV offset bit mask</xs:documentation></xs:annotation>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                    <xs:attribute name="name" type="g_string">
                                        <xs:annotation><xs:documentation xml:lang="en">Name of the variation</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="rootNode" type="g_node_index">
                                        <xs:annotation><xs:documentation xml:lang="en">Node that contains the variation data. Will be deleted if not used.</xs:documentation></xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>
